sudo: required
services:
  - docker
language: go
go: 1.11.6
script:
  - make build
  - make test
  - make pacts
  - make publish-pacts
after_success:
  - test -n "$TRAVIS_TAG" && make package_docker_docs
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
